### ISSUE TITLE
Differentiate between pages and Components.

### ISSUE THREAD

**Issue by B4BIPIN** [hidjou/classsed-react-firebase-client#1]
@hidjou, I am following your code and youtube channel quite from some days, but I have a small confusion in this code, **What is the role of creating two different folders name "pages" and "components" in your project?**

**Comment by hidjou** [comment]
It's a convention I picked up from working with a framework called gatsby, it doesn't change much, it's just a preference in organising the code base

**Comment by B4BIPIN** [comment]
Thanks, @hidjou.

**Comment by B4BIPIN** [comment]
Hi @hidjou, close this issue.
