### ISSUE TITLE
TypeError: Cannot read property 'handle' of undefined

### ISSUE THREAD

**Issue by orhys** [hidjou/classsed-react-firebase-client#12]
Hi, I am having issues with the rendering of the Profile component. It seems as though I am the data for credentials is undefined.

export class Profile extends Component {
  render() {
    const {
      classes,
      user: {
        **credentials: { handle, createdAt, imageUrl, bio, website, location },**
        loading,
        authenticated
      }
    } = this.props;

Below is a link to a Screencastify video. Help is much appreciated.

[https://drive.google.com/file/d/1iJGMIntIpB3qeYh-dZl_gOVh7Gd1tN6W/view](url)

**Comment by shinjiuan** [comment]
@orhys can I know how to solve this issue?
