### ISSUE TITLE
Error: Request failed with status code 403 - userActions.js:41

### ISSUE THREAD

**Issue by pigs-pigs** [hidjou/classsed-react-firebase-client#24]
I got:
Error: Request failed with status code 403                userActions.js:41    
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:61)

from my console and the profile section only says loading with no data! I think my code is all the same. I'm so confused please help!

EDIT: I think its working now but I'm getting an error on image upload...

**Comment by ghost** [comment]
Can you give me the solution ?

**Comment by pigs-pigs** [comment]
I don't recall what I did but eventually it just worked. I think i just did npm install and then served it and it worked
