### ISSUE TITLE
Application throws TypeError due redux dev tools doesn't installed

### ISSUE THREAD

**Issue by unref** [hidjou/classsed-react-firebase-client#4]
Hi, there is a problem. In case redux dev tools does not installed, app throws a `TypeError`.

It caused of this line:
https://github.com/hidjou/classsed-react-firebase-client/blob/a4c2a71f8482ca4c6bc2297377d7e53ed94c998b/src/redux/store.js#L23

In case redux dev tool not installed `windows.__REDUX_DEVTOOLS_EXTENSION__` returns undefined. Compose redux method does receive functions, and do not check either it function or not. Try to envoke apply on undefined goes to error.

As solution suppose move `window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()` out of compose().

https://github.com/zalmoxisus/redux-devtools-extension#12-advanced-store-setup

**Comment by hidjou** [comment]
I did remove that line in the deployed version, I forgot to set it up in the code base as well, I just did, thanks for raising the issue.
